# Templates used by AVD eos_designs role
default_templates:
  # Templates defined per design
  l3ls-evpn:
    facts:
      # Set "switch.*" variables based on node type
      - template: "facts/node_type/main.j2"
      # Set general "switch.*" variables
      - template: "facts/switch/main.j2"
    topology_facts:
      # Set design specific "topology.*" variables
      - template: "facts/topology/main.j2"
    structured_config:
      # Render Structured Configuration
      # Base features
      - template: "base/main.j2"
      # MLAG feature
      - template: "mlag/main.j2"
      # Underlay feature
      - template: "underlay/main.j2"
      # Overlay feature
      - template: "overlay/main.j2"
      # L3 Edge feature
      - template: "l3_edge/main.j2"
      # Tenants feature
      - template: "network_services/main.j2"
      # Connected Endpoints feature
      - template: "connected_endpoints/main.j2"
      # Inband Management feature
      - template: "inband_management/main.j2"
      # Merge custom_structured_configuration last
      - template: "custom_structured_configuration/main.j2"
        options:
          list_merge: "{{ custom_structured_configuration_list_merge }}"
          strip_empty_keys: false
    ip_addressing:
      router_id: 'ip_addressing/router-id.j2'
      mlag_ip_primary: 'ip_addressing/mlag-ip-primary.j2'
      mlag_ip_secondary: 'ip_addressing/mlag-ip-secondary.j2'
      mlag_l3_ip_primary: 'ip_addressing/mlag-l3-ip-primary.j2'
      mlag_l3_ip_secondary: 'ip_addressing/mlag-l3-ip-secondary.j2'
      p2p_uplinks_ip: 'ip_addressing/p2p-uplinks-ip.j2'
      p2p_uplinks_peer_ip: 'ip_addressing/p2p-uplinks-peer-ip.j2'
      vtep_ip_mlag: 'ip_addressing/vtep-ip-mlag.j2'
      vtep_ip: 'ip_addressing/vtep-ip.j2'

    interface_descriptions:
      underlay_ethernet_interfaces: 'interface_descriptions/underlay/ethernet-interfaces.j2'
      underlay_port_channel_interfaces: 'interface_descriptions/underlay/port-channel-interfaces.j2'
      connected_endpoints_ethernet_interfaces: 'interface_descriptions/connected_endpoints/ethernet-interfaces.j2'
      connected_endpoints_port_channel_interfaces: 'interface_descriptions/connected_endpoints/port-channel-interfaces.j2'
      overlay_loopback_interface: 'interface_descriptions/loopback_interfaces/overlay-loopback.j2'
      vtep_loopback_interface: 'interface_descriptions/loopback_interfaces/vtep-loopback.j2'

  mpls-vpn:
    facts:
      # Set "switch.*" variables based on node type
      - template: "facts/node_type/main.j2"
      # Set general "switch.*" variables
      - template: "facts/switch/main.j2"
      # Set general "switch.*" variables - FIXED
      # - template: "facts/main.j2"
      # Set design specific "switch.*" variables - FIXED
      # - template: "designs/mpls-vpn/facts/switch/main.j2"
    topology_facts:
      # Set design specific "topology.*" variables - FIXED
      # - template: "designs/mpls-vpn/facts/topology/main.j2"
      # Set design specific "topology.*" variables - FIXED
      - template: "facts/topology/main.j2"
    structured_config:
    # #   # Render Strucured Configuration
    # #   # Base features - FIXED
      - template: "base/main.j2"
    # #   # Underlay feature - FIXED
      - template: "designs/mpls-vpn/underlay/main.j2"
    # Backbone Interfaces
      - template: "backbone_interfaces/main.j2"
    # #   # Overlay feature - FIXED
      - template: "designs/mpls-vpn/overlay/main.j2"
    # #   # L3 Edge feature - FIXED/NO ACTION
      - template: "l3_edge/main.j2"
    # #   # Tenants feature
      - template: "designs/mpls-vpn/tenants/main.j2"
    # #   # Connected Endpoints feature
      - template: "connected_endpoints/main.j2"
    # #   # Inband Management feature
    # #   - template: "inband_management/main.j2"
    # #   # Merge custom_structured_configuration last
      - template: "custom_structured_configuration/main.j2"
        options:
          list_merge: "{{ custom_structured_configuration_list_merge }}"
          strip_empty_keys: false
    ip_addressing:
      router_id: 'ip_addressing/router-id.j2'
      p2p_uplinks_ip: 'ip_addressing/p2p-uplinks-ip.j2'
      ipv6_router_id: 'ip_addressing/router-id-ipv6.j2'
      # p2p_uplinks_peer_ip: 'designs/l3ls-evpn/ip-addressing/p2p-uplinks-peer-ip.j2'
      # p2p backbone link IP addressing is handled manually or with unnumbered options. No ipmath necessary atm.
      # p2p_backbone_links: 'designs/mpls-vpn/ip-addressing/p2p_backbone_links.j2'
    interface_descriptions:
      underlay_ethernet_interfaces: 'interface_descriptions/underlay/ethernet-interfaces.j2'
      underlay_port_channel_interfaces: 'interface_descriptions/underlay/port-channel-interfaces.j2'
      connected_endpoints_ethernet_interfaces: 'interface_descriptions/connected_endpoints/ethernet-interfaces.j2'
      connected_endpoints_port_channel_interfaces: 'interface_descriptions/connected_endpoints/port-channel-interfaces.j2'
      overlay_loopback_interface: 'interface_descriptions/loopback_interfaces/overlay-loopback.j2'
      vtep_loopback_interface: 'interface_descriptions/loopback_interfaces/vtep-loopback.j2'
