# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  mlag_configuration:
    type: dict
    keys:
      domain_id:
        type: str
      heartbeat_interval:
        type: int
        convert_types:
        - str
      local_interface:
        display_name: Interface Name
        type: str
      peer_address:
        type: str
      peer_address_heartbeat:
        type: dict
        keys:
          peer_ip:
            type: str
          vrf:
            display_name: VRF Name
            type: str
      dual_primary_detection_delay:
        type: int
        convert_types:
        - str
      dual_primary_recovery_delay_mlag:
        type: int
        min: 0
        max: 1000
        convert_types:
        - str
      dual_primary_recovery_delay_non_mlag:
        type: int
        min: 0
        max: 1000
        convert_types:
        - str
      peer_link:
        display_name: Port-Channel ID
        type: str
      reload_delay_mlag:
        type: int
        convert_types:
        - str
      reload_delay_non_mlag:
        type: int
        convert_types:
        - str
